Split implementation of tun_setaddr6 into a separate module
Some systems containing specific versions of libc and linux kernel can
produce compilation errors due to conflicting definition of structures
in different include files. This can be the case when including <netinet/in.h>
and <linux/in6.h>. See for more information:
https://sourceware.org/glibc/wiki/Synchronizing_Headers

I hit this compilation error on the system I'm compiling osmo-ggsn with:

arm-poky-linux-gnueabi-gcc ... -c in46_addr.c
In file included from /usr/include/linux/ipv6.h:5:0,
                 from tun.c:75:
/usr/include/linux/in6.h:30:8: error: redefinition of 'struct in6_addr'
 struct in6_addr {
        ^
In file included from tun.c:24:0:
/usr/include/netinet/in.h:196:8: note: originally defined here
 struct in6_addr
        ^

To fix the issue, this patch moves tun_setaddr6 to its own file which
then includes <linux/ipv6.h> (which in turn includes in6.h).

Change-Id: Ie161f376edda605e5cd87176169553176235fafd